services:
  iob.bank.api:
    container_name: iob.bank.api
    image: yurilucenaa/iob.api.host
    build:
      context: .
      dockerfile: Iob.Bank.Host/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=1234
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/iobcert.pfx
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - iob-network
    volumes:
      - ./Iob.Bank.Host/Cert:/https:ro
    depends_on:
      - iob.db

  iob.db:
    container_name: iob.db
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    networks:
      - iob-network
    ports:
      - "3306:3306"
    volumes:
      - "~/.dbiob:/var/lib/mysql"
networks:
  iob-network:
    name: iob-network
    driver: bridge
